name: Audit

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  merge_group:
    types: [checks_requested]

jobs:
  audit:
    needs: [cargo-deny-api, cargo-deny-types, cargo-deny-oauth2]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
      - name: Done
        run: exit 0

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.77.0  # Using highest MSRV for security checks
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit
      - run: cargo audit

  cargo-deny-api:
    name: Cargo Deny (twitch_api)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: 1.77.0
          command: check ${{ matrix.checks }} -s
          arguments: --all-features --package twitch_api
          log-level: warn

  cargo-deny-types:
    name: Cargo Deny (twitch_types)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: 1.67.0
          command: check ${{ matrix.checks }} -s
          arguments: --all-features --package twitch_types
          log-level: warn

  cargo-deny-oauth2:
    name: Cargo Deny (twitch_oauth2)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: 1.71.1
          command: check ${{ matrix.checks }} -s
          arguments: --all-features --package twitch_oauth2
          log-level: warn
